import React from 'react'

const About = () => {
  return (
    <div>
        <h1>About Page</h1>
        <p>Stet et ea amet sadipscing dolore justo sit nonumy voluptua. Stet erat dolor dolore aliquyam aliquyam et sanctus eirmod gubergren. Diam ea justo est takimata ut invidunt sit accusam ipsum, rebum stet dolor ipsum justo, dolor elitr dolor et amet lorem invidunt ea dolore. Vero amet diam sed accusam no amet. Rebum diam kasd amet sea et takimata dolore ipsum, ea sea justo justo et dolores lorem lorem elitr, sed amet est et takimata diam justo. Sanctus sea dolores vero et diam lorem elitr. Invidunt vero clita erat at diam, sed eos eirmod vero dolor elitr sed. Duo eos rebum sit amet clita et sed, eirmod eos elitr diam eirmod, eos est dolor dolore tempor accusam justo, lorem sed clita erat sit labore voluptua. Et sed lorem dolor duo aliquyam no. Vero gubergren magna diam labore sadipscing sit erat sed ut, no et duo stet magna stet sanctus accusam. Justo sit sed lorem lorem sed no. Nonumy dolor et magna sea takimata amet dolor erat sit. Voluptua diam lorem rebum justo voluptua accusam eirmod kasd, at vero at elitr dolore eirmod dolor elitr, erat eirmod invidunt lorem erat dolor invidunt lorem. Eirmod sea sanctus sadipscing et amet dolores gubergren justo. Takimata diam dolor dolores ut ea est amet, sed magna et lorem aliquyam lorem. Labore sanctus amet sed et et gubergren, gubergren clita sed duo et, sit vero amet tempor dolores elitr sed, sit amet lorem rebum est et kasd ea eos consetetur. Aliquyam aliquyam ipsum ipsum dolores et voluptua sea no sanctus, dolor dolores diam dolore stet, sit aliquyam clita eirmod et lorem. Ut dolores lorem lorem no clita labore takimata nonumy duo. Stet dolores ut lorem diam dolore gubergren stet sed dolores. Sed rebum eos diam vero sed et duo eirmod eirmod. Duo eirmod lorem diam sanctus dolor. Eos nonumy no ipsum takimata diam sit. Justo sed dolor et takimata amet. Nonumy nonumy sed aliquyam labore duo duo voluptua ut sed. Accusam dolor diam eirmod amet aliquyam eos clita sit takimata. Dolor magna tempor et stet ut, eirmod stet amet justo voluptua amet justo et. Dolore tempor et amet lorem. Labore voluptua dolores sit sea dolor et. Tempor sadipscing voluptua aliquyam labore sadipscing dolor erat vero. Et dolore lorem justo amet gubergren erat sed. Sea amet gubergren duo nonumy. Dolor clita sit sadipscing eos ipsum rebum stet sadipscing at, gubergren rebum eos voluptua amet rebum amet et ipsum, stet nonumy at rebum rebum kasd dolore sit voluptua vero, gubergren aliquyam ut clita rebum ipsum et. Voluptua no sanctus sanctus et stet invidunt dolor stet. Est dolor sadipscing at sit ea. Clita justo ut diam nonumy stet justo sanctus, sed invidunt voluptua sed aliquyam eirmod voluptua lorem, rebum dolores lorem sadipscing sadipscing et. Eirmod accusam eos justo consetetur dolor sed, kasd ut ipsum ipsum rebum no amet ipsum. Sadipscing sit amet ipsum ipsum stet amet, kasd est sadipscing eirmod gubergren sit diam, sed et et lorem erat labore, duo dolor amet ut clita lorem aliquyam, sadipscing amet duo et.</p>
    </div>
  )
}

export default About