import React from 'react'

const Home = () => {
    return (
        <div>
            <h1>Blog 1</h1>
            <p>Diam dolor elitr dolor sed sea sadipscing duo sea dolor. Eos voluptua dolores kasd amet diam ea lorem labore. Rebum et diam duo nonumy et diam dolor ea, erat sed et nonumy lorem stet erat. Rebum est eirmod erat magna tempor et. Duo ipsum duo eirmod dolor clita et diam. Duo sadipscing rebum est sit amet, sit dolor et eos sit duo et, takimata justo dolore dolor kasd. Sit kasd voluptua et eirmod. Duo accusam at at ipsum eirmod stet no. Est dolores sed ipsum ipsum labore ipsum. Gubergren diam stet eirmod rebum dolor sit. Dolores amet at sea justo invidunt erat diam at. Diam clita stet sed ipsum aliquyam amet dolor et, elitr dolores dolores nonumy lorem et sea voluptua, takimata dolor sed sea kasd amet amet, dolor et magna diam sed. Ea et ipsum takimata no. Dolores sit no lorem sit lorem justo dolore. Invidunt et lorem diam et, rebum kasd eirmod clita justo ea ea sea, et voluptua kasd dolores lorem invidunt rebum vero elitr. Dolore takimata elitr gubergren sit amet. Tempor accusam diam kasd consetetur et, kasd et aliquyam sanctus sanctus dolores est, at diam ea diam sadipscing rebum eirmod amet est rebum. Accusam diam ut nonumy dolore erat ipsum justo ipsum ipsum. Amet elitr accusam elitr et sanctus et amet rebum lorem, dolor dolore sea no dolore labore sit kasd labore vero. Sanctus dolore sit diam duo tempor magna ipsum dolor. Eos kasd et clita dolore diam voluptua sea, gubergren elitr aliquyam takimata erat sit dolor clita. Accusam ut accusam sanctus et ea, accusam ipsum sit labore eirmod elitr diam ipsum consetetur takimata. Sea rebum sit et sanctus sed sadipscing eirmod erat. Sadipscing duo eirmod erat sanctus dolore et et stet. Dolor no vero voluptua kasd. Sadipscing sed et sit et vero sed takimata kasd, justo lorem dolores eos sea consetetur. Gubergren et accusam elitr rebum est sed stet, amet gubergren consetetur labore invidunt erat. Aliquyam kasd lorem amet invidunt sanctus rebum amet et. At et takimata et takimata, ut tempor lorem accusam elitr justo. Dolores at sanctus consetetur labore amet. Justo clita vero ipsum at consetetur, rebum lorem et dolores at, diam dolor sadipscing ipsum sanctus, et magna sed sea ipsum, eirmod sed et diam justo diam sed et justo at, dolores erat erat no invidunt, at sit lorem elitr sanctus est sed. At ipsum et et amet ea ipsum sea dolore at, magna voluptua sit voluptua sit dolor. Eos no stet at stet ut, dolores dolor aliquyam vero sanctus. Voluptua sed consetetur ut dolore nonumy voluptua justo accusam dolor, voluptua takimata lorem elitr magna. Aliquyam lorem nonumy et justo sanctus magna. Clita justo consetetur ut dolores sanctus rebum, et nonumy ut clita dolor eirmod sanctus. Duo et magna justo et, dolores at et accusam voluptua duo, kasd diam lorem lorem est elitr diam eos erat, accusam ea voluptua voluptua sed consetetur invidunt, sed sea consetetur lorem sed stet, labore eirmod ipsum consetetur sea, labore magna sed duo sit dolore, invidunt amet et sea.</p><br/>
            <h1>Blog 2</h1>
            <p>Justo magna et aliquyam nonumy accusam dolor takimata et amet, et dolores amet sed clita justo, diam aliquyam vero clita kasd dolor invidunt consetetur sit vero. Et elitr dolor magna diam diam vero sed sed. Kasd duo eirmod tempor consetetur diam takimata, aliquyam dolore rebum rebum at lorem ea elitr, rebum labore ea labore labore diam gubergren. Rebum vero est no duo dolore rebum, dolor clita sit et vero sea diam, amet sed sed lorem kasd lorem sanctus sed. Sanctus tempor sadipscing duo kasd sit vero aliquyam tempor diam. Justo diam est labore justo kasd sed aliquyam sanctus. Est ipsum sit sed est. Invidunt vero ea magna rebum duo. Dolor dolor duo et accusam diam elitr sadipscing sea. Tempor eos voluptua nonumy labore lorem. Rebum et justo ipsum magna elitr stet accusam diam, consetetur consetetur ipsum rebum duo labore dolore. Gubergren dolor sed rebum kasd ipsum. Et duo sanctus dolor justo kasd. Magna lorem justo dolores at at accusam vero. Justo et stet ea ut sanctus et lorem rebum. Et gubergren ea erat diam invidunt dolores erat lorem ea, sed takimata amet ipsum et sit clita diam, labore sed eos lorem sit tempor sit sit. Ipsum labore no amet eos est dolor diam, lorem et sit et et amet, est sanctus magna et eos dolore, sed elitr et lorem amet justo accusam. Et accusam eos at ut tempor dolore ipsum amet magna. Diam sed ipsum clita lorem et, amet at invidunt labore ut sadipscing, magna invidunt elitr erat est. Voluptua ipsum consetetur kasd diam eos et eirmod dolor. Voluptua sea nonumy clita ipsum magna rebum, amet dolores kasd erat diam et ipsum ipsum, amet takimata nonumy sadipscing takimata lorem justo et, labore vero labore amet at justo consetetur, clita voluptua et sed eirmod dolores et diam. Ipsum consetetur amet consetetur amet ipsum est tempor et. Magna elitr diam ipsum sit sed. Labore ipsum rebum invidunt elitr magna eos amet. Clita nonumy erat at gubergren stet invidunt, ea sea et sadipscing justo sea labore et ut ipsum, ea et tempor accusam duo dolore sit, sanctus tempor tempor dolores eos est, no eos dolor et sit est duo amet, ut justo dolore diam sadipscing. Ipsum dolor et et gubergren takimata. Tempor kasd ipsum dolor nonumy ut sadipscing et. Nonumy amet at sadipscing sit. Aliquyam et lorem ipsum amet labore erat sit eirmod sit. Amet erat lorem ut lorem tempor nonumy sea, amet erat ut stet sed ipsum clita gubergren rebum et, sed sit est est vero eos, tempor et accusam amet est et duo dolore sed, voluptua ea labore et et sanctus et ut. Aliquyam duo ipsum takimata accusam tempor lorem. Diam voluptua lorem aliquyam sed ipsum sed at diam. Invidunt consetetur sit sadipscing dolor sit dolor clita takimata amet. At no dolore rebum eirmod. Ea labore sed est sit. Nonumy aliquyam et no et kasd consetetur. Gubergren ut sea at amet consetetur sit sit aliquyam sit, takimata nonumy tempor duo rebum et, et nonumy sit dolores tempor, ea justo at lorem.</p>
        </div>
    )
}

export default Home