export const blogsData = [
    {
        id: 1,
        title: "html",
        body: "Diam justo amet et sit lorem, sanctus elitr dolores sadipscing ipsum rebum sed voluptua justo lorem. Sit sadipscing eirmod duo amet. Sit gubergren sanctus nonumy dolor. Et diam sed sea sed eos tempor. Justo at dolor lorem consetetur est duo sit, labore voluptua lorem clita labore dolor amet elitr labore invidunt, ea diam no no dolor accusam amet labore magna, nonumy et dolore ipsum justo elitr et. Diam stet elitr sanctus et ut et lorem dolore, gubergren labore sed gubergren justo voluptua eirmod elitr dolore, duo clita sed dolores diam ea clita at. Dolor vero diam diam gubergren ut lorem ea, stet accusam accusam takimata sit lorem vero ea, invidunt diam sit amet ut takimata. Duo kasd voluptua ut dolor, magna diam justo et no aliquyam. Dolor diam gubergren diam ea, rebum ea accusam et eirmod stet. Ipsum ut erat at sed. Justo aliquyam accusam sanctus lorem ea, eirmod voluptua et et nonumy tempor et, justo ipsum vero justo justo et elitr sanctus. Magna et amet kasd sanctus diam, rebum ipsum dolor diam vero sea, magna no sit eos et takimata invidunt ipsum lorem eos, nonumy sed tempor labore invidunt sea sit vero. Ea duo dolor erat dolor dolor diam elitr gubergren duo. Takimata diam duo et stet sit kasd, diam et stet sadipscing justo. Et labore labore sed duo stet rebum eos. Diam ipsum tempor sit rebum diam takimata elitr sed takimata, duo sed takimata justo sit magna et et gubergren voluptua. Diam elitr est at sadipscing, magna labore ut dolor rebum et ipsum vero sed at, sit lorem dolores nonumy justo nonumy. Nonumy vero gubergren diam no, sit sed no at lorem amet diam duo sed stet, et tempor sed sed tempor eos lorem. Elitr sit et kasd eirmod amet amet. Et et aliquyam sed voluptua lorem kasd."
    },
    {
        id: 2,
        title: "css",
        body: "Diam justo amet et sit lorem, sanctus elitr dolores sadipscing ipsum rebum sed voluptua justo lorem. Sit sadipscing eirmod duo amet. Sit gubergren sanctus nonumy dolor. Et diam sed sea sed eos tempor. Justo at dolor lorem consetetur est duo sit, labore voluptua lorem clita labore dolor amet elitr labore invidunt, ea diam no no dolor accusam amet labore magna, nonumy et dolore ipsum justo elitr et. Diam stet elitr sanctus et ut et lorem dolore, gubergren labore sed gubergren justo voluptua eirmod elitr dolore, duo clita sed dolores diam ea clita at. Dolor vero diam diam gubergren ut lorem ea, stet accusam accusam takimata sit lorem vero ea, invidunt diam sit amet ut takimata. Duo kasd voluptua ut dolor, magna diam justo et no aliquyam. Dolor diam gubergren diam ea, rebum ea accusam et eirmod stet. Ipsum ut erat at sed. Justo aliquyam accusam sanctus lorem ea, eirmod voluptua et et nonumy tempor et, justo ipsum vero justo justo et elitr sanctus. Magna et amet kasd sanctus diam, rebum ipsum dolor diam vero sea, magna no sit eos et takimata invidunt ipsum lorem eos, nonumy sed tempor labore invidunt sea sit vero. Ea duo dolor erat dolor dolor diam elitr gubergren duo. Takimata diam duo et stet sit kasd, diam et stet sadipscing justo. Et labore labore sed duo stet rebum eos. Diam ipsum tempor sit rebum diam takimata elitr sed takimata, duo sed takimata justo sit magna et et gubergren voluptua. Diam elitr est at sadipscing, magna labore ut dolor rebum et ipsum vero sed at, sit lorem dolores nonumy justo nonumy. Nonumy vero gubergren diam no, sit sed no at lorem amet diam duo sed stet, et tempor sed sed tempor eos lorem. Elitr sit et kasd eirmod amet amet. Et et aliquyam sed voluptua lorem kasd."
    },
    {
        id: 3,
        title: "bootstrap",
        body: "Diam justo amet et sit lorem, sanctus elitr dolores sadipscing ipsum rebum sed voluptua justo lorem. Sit sadipscing eirmod duo amet. Sit gubergren sanctus nonumy dolor. Et diam sed sea sed eos tempor. Justo at dolor lorem consetetur est duo sit, labore voluptua lorem clita labore dolor amet elitr labore invidunt, ea diam no no dolor accusam amet labore magna, nonumy et dolore ipsum justo elitr et. Diam stet elitr sanctus et ut et lorem dolore, gubergren labore sed gubergren justo voluptua eirmod elitr dolore, duo clita sed dolores diam ea clita at. Dolor vero diam diam gubergren ut lorem ea, stet accusam accusam takimata sit lorem vero ea, invidunt diam sit amet ut takimata. Duo kasd voluptua ut dolor, magna diam justo et no aliquyam. Dolor diam gubergren diam ea, rebum ea accusam et eirmod stet. Ipsum ut erat at sed. Justo aliquyam accusam sanctus lorem ea, eirmod voluptua et et nonumy tempor et, justo ipsum vero justo justo et elitr sanctus. Magna et amet kasd sanctus diam, rebum ipsum dolor diam vero sea, magna no sit eos et takimata invidunt ipsum lorem eos, nonumy sed tempor labore invidunt sea sit vero. Ea duo dolor erat dolor dolor diam elitr gubergren duo. Takimata diam duo et stet sit kasd, diam et stet sadipscing justo. Et labore labore sed duo stet rebum eos. Diam ipsum tempor sit rebum diam takimata elitr sed takimata, duo sed takimata justo sit magna et et gubergren voluptua. Diam elitr est at sadipscing, magna labore ut dolor rebum et ipsum vero sed at, sit lorem dolores nonumy justo nonumy. Nonumy vero gubergren diam no, sit sed no at lorem amet diam duo sed stet, et tempor sed sed tempor eos lorem. Elitr sit et kasd eirmod amet amet. Et et aliquyam sed voluptua lorem kasd."
    },
    {
        id: 4,
        title: "php",
        body: "Diam justo amet et sit lorem, sanctus elitr dolores sadipscing ipsum rebum sed voluptua justo lorem. Sit sadipscing eirmod duo amet. Sit gubergren sanctus nonumy dolor. Et diam sed sea sed eos tempor. Justo at dolor lorem consetetur est duo sit, labore voluptua lorem clita labore dolor amet elitr labore invidunt, ea diam no no dolor accusam amet labore magna, nonumy et dolore ipsum justo elitr et. Diam stet elitr sanctus et ut et lorem dolore, gubergren labore sed gubergren justo voluptua eirmod elitr dolore, duo clita sed dolores diam ea clita at. Dolor vero diam diam gubergren ut lorem ea, stet accusam accusam takimata sit lorem vero ea, invidunt diam sit amet ut takimata. Duo kasd voluptua ut dolor, magna diam justo et no aliquyam. Dolor diam gubergren diam ea, rebum ea accusam et eirmod stet. Ipsum ut erat at sed. Justo aliquyam accusam sanctus lorem ea, eirmod voluptua et et nonumy tempor et, justo ipsum vero justo justo et elitr sanctus. Magna et amet kasd sanctus diam, rebum ipsum dolor diam vero sea, magna no sit eos et takimata invidunt ipsum lorem eos, nonumy sed tempor labore invidunt sea sit vero. Ea duo dolor erat dolor dolor diam elitr gubergren duo. Takimata diam duo et stet sit kasd, diam et stet sadipscing justo. Et labore labore sed duo stet rebum eos. Diam ipsum tempor sit rebum diam takimata elitr sed takimata, duo sed takimata justo sit magna et et gubergren voluptua. Diam elitr est at sadipscing, magna labore ut dolor rebum et ipsum vero sed at, sit lorem dolores nonumy justo nonumy. Nonumy vero gubergren diam no, sit sed no at lorem amet diam duo sed stet, et tempor sed sed tempor eos lorem. Elitr sit et kasd eirmod amet amet. Et et aliquyam sed voluptua lorem kasd."
    },
    {
        id: 5,
        title: "java",
        body: "Diam justo amet et sit lorem, sanctus elitr dolores sadipscing ipsum rebum sed voluptua justo lorem. Sit sadipscing eirmod duo amet. Sit gubergren sanctus nonumy dolor. Et diam sed sea sed eos tempor. Justo at dolor lorem consetetur est duo sit, labore voluptua lorem clita labore dolor amet elitr labore invidunt, ea diam no no dolor accusam amet labore magna, nonumy et dolore ipsum justo elitr et. Diam stet elitr sanctus et ut et lorem dolore, gubergren labore sed gubergren justo voluptua eirmod elitr dolore, duo clita sed dolores diam ea clita at. Dolor vero diam diam gubergren ut lorem ea, stet accusam accusam takimata sit lorem vero ea, invidunt diam sit amet ut takimata. Duo kasd voluptua ut dolor, magna diam justo et no aliquyam. Dolor diam gubergren diam ea, rebum ea accusam et eirmod stet. Ipsum ut erat at sed. Justo aliquyam accusam sanctus lorem ea, eirmod voluptua et et nonumy tempor et, justo ipsum vero justo justo et elitr sanctus. Magna et amet kasd sanctus diam, rebum ipsum dolor diam vero sea, magna no sit eos et takimata invidunt ipsum lorem eos, nonumy sed tempor labore invidunt sea sit vero. Ea duo dolor erat dolor dolor diam elitr gubergren duo. Takimata diam duo et stet sit kasd, diam et stet sadipscing justo. Et labore labore sed duo stet rebum eos. Diam ipsum tempor sit rebum diam takimata elitr sed takimata, duo sed takimata justo sit magna et et gubergren voluptua. Diam elitr est at sadipscing, magna labore ut dolor rebum et ipsum vero sed at, sit lorem dolores nonumy justo nonumy. Nonumy vero gubergren diam no, sit sed no at lorem amet diam duo sed stet, et tempor sed sed tempor eos lorem. Elitr sit et kasd eirmod amet amet. Et et aliquyam sed voluptua lorem kasd."
    },
    {
        id: 6,
        title: "python",
        body: "Diam justo amet et sit lorem, sanctus elitr dolores sadipscing ipsum rebum sed voluptua justo lorem. Sit sadipscing eirmod duo amet. Sit gubergren sanctus nonumy dolor. Et diam sed sea sed eos tempor. Justo at dolor lorem consetetur est duo sit, labore voluptua lorem clita labore dolor amet elitr labore invidunt, ea diam no no dolor accusam amet labore magna, nonumy et dolore ipsum justo elitr et. Diam stet elitr sanctus et ut et lorem dolore, gubergren labore sed gubergren justo voluptua eirmod elitr dolore, duo clita sed dolores diam ea clita at. Dolor vero diam diam gubergren ut lorem ea, stet accusam accusam takimata sit lorem vero ea, invidunt diam sit amet ut takimata. Duo kasd voluptua ut dolor, magna diam justo et no aliquyam. Dolor diam gubergren diam ea, rebum ea accusam et eirmod stet. Ipsum ut erat at sed. Justo aliquyam accusam sanctus lorem ea, eirmod voluptua et et nonumy tempor et, justo ipsum vero justo justo et elitr sanctus. Magna et amet kasd sanctus diam, rebum ipsum dolor diam vero sea, magna no sit eos et takimata invidunt ipsum lorem eos, nonumy sed tempor labore invidunt sea sit vero. Ea duo dolor erat dolor dolor diam elitr gubergren duo. Takimata diam duo et stet sit kasd, diam et stet sadipscing justo. Et labore labore sed duo stet rebum eos. Diam ipsum tempor sit rebum diam takimata elitr sed takimata, duo sed takimata justo sit magna et et gubergren voluptua. Diam elitr est at sadipscing, magna labore ut dolor rebum et ipsum vero sed at, sit lorem dolores nonumy justo nonumy. Nonumy vero gubergren diam no, sit sed no at lorem amet diam duo sed stet, et tempor sed sed tempor eos lorem. Elitr sit et kasd eirmod amet amet. Et et aliquyam sed voluptua lorem kasd."
    },
    {
        id: 7,
        title: "javascript",
        body: "Diam justo amet et sit lorem, sanctus elitr dolores sadipscing ipsum rebum sed voluptua justo lorem. Sit sadipscing eirmod duo amet. Sit gubergren sanctus nonumy dolor. Et diam sed sea sed eos tempor. Justo at dolor lorem consetetur est duo sit, labore voluptua lorem clita labore dolor amet elitr labore invidunt, ea diam no no dolor accusam amet labore magna, nonumy et dolore ipsum justo elitr et. Diam stet elitr sanctus et ut et lorem dolore, gubergren labore sed gubergren justo voluptua eirmod elitr dolore, duo clita sed dolores diam ea clita at. Dolor vero diam diam gubergren ut lorem ea, stet accusam accusam takimata sit lorem vero ea, invidunt diam sit amet ut takimata. Duo kasd voluptua ut dolor, magna diam justo et no aliquyam. Dolor diam gubergren diam ea, rebum ea accusam et eirmod stet. Ipsum ut erat at sed. Justo aliquyam accusam sanctus lorem ea, eirmod voluptua et et nonumy tempor et, justo ipsum vero justo justo et elitr sanctus. Magna et amet kasd sanctus diam, rebum ipsum dolor diam vero sea, magna no sit eos et takimata invidunt ipsum lorem eos, nonumy sed tempor labore invidunt sea sit vero. Ea duo dolor erat dolor dolor diam elitr gubergren duo. Takimata diam duo et stet sit kasd, diam et stet sadipscing justo. Et labore labore sed duo stet rebum eos. Diam ipsum tempor sit rebum diam takimata elitr sed takimata, duo sed takimata justo sit magna et et gubergren voluptua. Diam elitr est at sadipscing, magna labore ut dolor rebum et ipsum vero sed at, sit lorem dolores nonumy justo nonumy. Nonumy vero gubergren diam no, sit sed no at lorem amet diam duo sed stet, et tempor sed sed tempor eos lorem. Elitr sit et kasd eirmod amet amet. Et et aliquyam sed voluptua lorem kasd."
    },
    {
        id: 8,
        title: "laravel",
        body: "Diam justo amet et sit lorem, sanctus elitr dolores sadipscing ipsum rebum sed voluptua justo lorem. Sit sadipscing eirmod duo amet. Sit gubergren sanctus nonumy dolor. Et diam sed sea sed eos tempor. Justo at dolor lorem consetetur est duo sit, labore voluptua lorem clita labore dolor amet elitr labore invidunt, ea diam no no dolor accusam amet labore magna, nonumy et dolore ipsum justo elitr et. Diam stet elitr sanctus et ut et lorem dolore, gubergren labore sed gubergren justo voluptua eirmod elitr dolore, duo clita sed dolores diam ea clita at. Dolor vero diam diam gubergren ut lorem ea, stet accusam accusam takimata sit lorem vero ea, invidunt diam sit amet ut takimata. Duo kasd voluptua ut dolor, magna diam justo et no aliquyam. Dolor diam gubergren diam ea, rebum ea accusam et eirmod stet. Ipsum ut erat at sed. Justo aliquyam accusam sanctus lorem ea, eirmod voluptua et et nonumy tempor et, justo ipsum vero justo justo et elitr sanctus. Magna et amet kasd sanctus diam, rebum ipsum dolor diam vero sea, magna no sit eos et takimata invidunt ipsum lorem eos, nonumy sed tempor labore invidunt sea sit vero. Ea duo dolor erat dolor dolor diam elitr gubergren duo. Takimata diam duo et stet sit kasd, diam et stet sadipscing justo. Et labore labore sed duo stet rebum eos. Diam ipsum tempor sit rebum diam takimata elitr sed takimata, duo sed takimata justo sit magna et et gubergren voluptua. Diam elitr est at sadipscing, magna labore ut dolor rebum et ipsum vero sed at, sit lorem dolores nonumy justo nonumy. Nonumy vero gubergren diam no, sit sed no at lorem amet diam duo sed stet, et tempor sed sed tempor eos lorem. Elitr sit et kasd eirmod amet amet. Et et aliquyam sed voluptua lorem kasd."
    },
    {
        id: 9,
        title: "react.js",
        body: "Diam justo amet et sit lorem, sanctus elitr dolores sadipscing ipsum rebum sed voluptua justo lorem. Sit sadipscing eirmod duo amet. Sit gubergren sanctus nonumy dolor. Et diam sed sea sed eos tempor. Justo at dolor lorem consetetur est duo sit, labore voluptua lorem clita labore dolor amet elitr labore invidunt, ea diam no no dolor accusam amet labore magna, nonumy et dolore ipsum justo elitr et. Diam stet elitr sanctus et ut et lorem dolore, gubergren labore sed gubergren justo voluptua eirmod elitr dolore, duo clita sed dolores diam ea clita at. Dolor vero diam diam gubergren ut lorem ea, stet accusam accusam takimata sit lorem vero ea, invidunt diam sit amet ut takimata. Duo kasd voluptua ut dolor, magna diam justo et no aliquyam. Dolor diam gubergren diam ea, rebum ea accusam et eirmod stet. Ipsum ut erat at sed. Justo aliquyam accusam sanctus lorem ea, eirmod voluptua et et nonumy tempor et, justo ipsum vero justo justo et elitr sanctus. Magna et amet kasd sanctus diam, rebum ipsum dolor diam vero sea, magna no sit eos et takimata invidunt ipsum lorem eos, nonumy sed tempor labore invidunt sea sit vero. Ea duo dolor erat dolor dolor diam elitr gubergren duo. Takimata diam duo et stet sit kasd, diam et stet sadipscing justo. Et labore labore sed duo stet rebum eos. Diam ipsum tempor sit rebum diam takimata elitr sed takimata, duo sed takimata justo sit magna et et gubergren voluptua. Diam elitr est at sadipscing, magna labore ut dolor rebum et ipsum vero sed at, sit lorem dolores nonumy justo nonumy. Nonumy vero gubergren diam no, sit sed no at lorem amet diam duo sed stet, et tempor sed sed tempor eos lorem. Elitr sit et kasd eirmod amet amet. Et et aliquyam sed voluptua lorem kasd."
    },
    {
        id: 10,
        title: "mysql",
        body: "Diam justo amet et sit lorem, sanctus elitr dolores sadipscing ipsum rebum sed voluptua justo lorem. Sit sadipscing eirmod duo amet. Sit gubergren sanctus nonumy dolor. Et diam sed sea sed eos tempor. Justo at dolor lorem consetetur est duo sit, labore voluptua lorem clita labore dolor amet elitr labore invidunt, ea diam no no dolor accusam amet labore magna, nonumy et dolore ipsum justo elitr et. Diam stet elitr sanctus et ut et lorem dolore, gubergren labore sed gubergren justo voluptua eirmod elitr dolore, duo clita sed dolores diam ea clita at. Dolor vero diam diam gubergren ut lorem ea, stet accusam accusam takimata sit lorem vero ea, invidunt diam sit amet ut takimata. Duo kasd voluptua ut dolor, magna diam justo et no aliquyam. Dolor diam gubergren diam ea, rebum ea accusam et eirmod stet. Ipsum ut erat at sed. Justo aliquyam accusam sanctus lorem ea, eirmod voluptua et et nonumy tempor et, justo ipsum vero justo justo et elitr sanctus. Magna et amet kasd sanctus diam, rebum ipsum dolor diam vero sea, magna no sit eos et takimata invidunt ipsum lorem eos, nonumy sed tempor labore invidunt sea sit vero. Ea duo dolor erat dolor dolor diam elitr gubergren duo. Takimata diam duo et stet sit kasd, diam et stet sadipscing justo. Et labore labore sed duo stet rebum eos. Diam ipsum tempor sit rebum diam takimata elitr sed takimata, duo sed takimata justo sit magna et et gubergren voluptua. Diam elitr est at sadipscing, magna labore ut dolor rebum et ipsum vero sed at, sit lorem dolores nonumy justo nonumy. Nonumy vero gubergren diam no, sit sed no at lorem amet diam duo sed stet, et tempor sed sed tempor eos lorem. Elitr sit et kasd eirmod amet amet. Et et aliquyam sed voluptua lorem kasd."
    }

]